apiVersion: v1
kind: ConfigMap
metadata:
  name: rt-slurm-conf
  namespace: default
data:
  SLURM_CONTROLMACHINE: rt-slurmctld
  SLURM_NODENAME: rt-slurmctld,rt-slurmd1
---
kind: Service
apiVersion: v1
metadata:
  name: rt-slurmctld-np
spec:
  type: NodePort
  selector:
    name: rt-slurmctld
  ports:
    - port: 22
      name: myssh
      targetPort: 22
      nodePort: 30222
---
apiVersion: v1
kind: Service
metadata:
  name: rt-slurmctld
spec:
  clusterIP: None
  selector:
    name: rt-slurmctld
  ports:
     - name: "6817"     
       port: 6817
     - name: "6818"
       port: 6818
     - name: "6819"       
       port: 6819
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: rt-slurmctld
  labels:
    name: rt-slurmctld
spec:
  replicas: 1
  selector:
    name: rt-slurmctld
  template:
    metadata:
      labels:
        name: rt-slurmctld
    spec:
      hostname: rt-slurmctld
      containers:
        - name: rt-slurmctld
          image: allexy/slurm-image
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["/usr/sbin/init"]
          env:
            - name: SLURM_NODE_TYPE
              value: slurmctld
            - name: SLURM_CONTROLMACHINE
              valueFrom:
                configMapKeyRef:
                  name: rt-slurm-conf
                  key: SLURM_CONTROLMACHINE
            - name: SLURM_NODENAME
              valueFrom:
                configMapKeyRef:
                  name: rt-slurm-conf
                  key: SLURM_NODENAME
          ports:
            - containerPort: 22
            - containerPort: 6817
            - containerPort: 6818
            - containerPort: 6819
          volumeMounts:   
            - mountPath: /etc/localtime
              name: rt-datetime
              readOnly: false
            - mountPath: /rt/usr
              name: rt-usr
              readOnly: false
      volumes:
        - name: rt-datetime
          hostPath:
            path: /etc/localtime
        - name: rt-usr
          hostPath:
            path: /rt/usr
      restartPolicy: Always
      nodeSelector:
          node: omnisky
---
apiVersion: v1
kind: Service
metadata:
  name: rt-slurmd1
spec:
  clusterIP: None
  selector:
    name: rt-slurmd1
  ports:
     - name: "6817"     
       port: 6817
     - name: "6818"
       port: 6818
     - name: "6819"       
       port: 6819
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: rt-slurmd1
  labels:
    name: rt-slurmd1
spec:
  replicas: 1
  selector:
    name: rt-slurmd1
  template:
    metadata:
      labels:
        name: rt-slurmd1
    spec:
      hostname: rt-slurmd1
      containers:
        - name: rt-slurmd1
          image: allexy/slurm-image
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["/usr/sbin/init"]
          env:
            - name: SLURM_NODE_TYPE
              value: slurmd
            - name: SLURM_CONTROLMACHINE
              valueFrom:
                configMapKeyRef:
                  name: rt-slurm-conf
                  key: SLURM_CONTROLMACHINE
            - name: SLURM_NODENAME
              valueFrom:
                configMapKeyRef:
                  name: rt-slurm-conf
                  key: SLURM_NODENAME
          ports:
            - containerPort: 22
            - containerPort: 6817
            - containerPort: 6818
            - containerPort: 6819
          volumeMounts:   
            - mountPath: /etc/localtime
              name: rt-datetime
              readOnly: false
            - mountPath: /rt/usr
              name: rt-usr
              readOnly: false
      volumes:
        - name: rt-datetime
          hostPath:
            path: /etc/localtime
        - name: rt-usr
          hostPath:
            path: /rt/usr
      restartPolicy: Always
      nodeSelector:
          node: node01